/**
 * Catalogo del cliente.
 *
 * Generado por scripts/preparar-catalogo.mjs a partir de:
 *   MODELOS MAS VENDIOS +  MODELOS VARIADOS (1).pdf
 *
 * NO se edita a mano: se vuelve a generar con  npm run catalogo.
 */

export type FilaCatalogo = {
  codigo: string;
  descripcion: string;
  categoria: string;
  tela: string;
  tallas: string;
  colores: string;
  foto: string;
  notas: string;
  destacado: number;
};

export const ORIGEN = "MODELOS MAS VENDIOS +  MODELOS VARIADOS (1).pdf";

export const CATALOGO: FilaCatalogo[] = [
  {
    "codigo": "VD 194",
    "descripcion": "VESTIDO MIDI OLANES",
    "categoria": "VESTIDO",
    "tela": "POWER SATEN",
    "tallas": "GDE - XL - 2XL",
    "colores": "VARIADO",
    "foto": "/catalogo/VD194.jpg",
    "notas": "Descripcion: VESTIDO MIDI OLANES + FAJO\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS\nAvios: ETIQUETA PARADA",
    "destacado": 1
  },
  {
    "codigo": "084",
    "descripcion": "VESTIDO MAXI DE COPAS SATEN",
    "categoria": "VESTIDO",
    "tela": "POWER SATEN",
    "tallas": "CH - M - GDE",
    "colores": "VARIADO",
    "foto": "/catalogo/084.jpg",
    "notas": "Descripcion: VESTIDO LARGO CON ESCOTE CRUZADO CON TABLONES Y FALDA CON DRAPEADO\nProveedor: NELLY",
    "destacado": 1
  },
  {
    "codigo": "VD 302",
    "descripcion": "VESTIDO MANGA MARIPOSA",
    "categoria": "VESTIDO",
    "tela": "POWER SATEN",
    "tallas": "GDE - XL - 2XL",
    "colores": "VARIADO",
    "foto": "/catalogo/VD302.jpg",
    "notas": "Descripcion: MAXI PETO PLISADO Y MANGA CON VUELO",
    "destacado": 1
  },
  {
    "codigo": "VD 342",
    "descripcion": "VESTIDO MIDI CAMPESINO",
    "categoria": "VESTIDO",
    "tela": "POWER SATEN",
    "tallas": "M - GDE - XL",
    "colores": "VARIADO",
    "foto": "/catalogo/VD342.jpg",
    "notas": "Descripcion: VESTIDO MIDI CON OLAN",
    "destacado": 1
  },
  {
    "codigo": "004",
    "descripcion": "VESTIDO SATEN VUELO CORTO",
    "categoria": "VESTIDO",
    "tela": "POWER SATEN",
    "tallas": "CH - M - GDE - XL",
    "colores": "VARIADO",
    "foto": "/catalogo/004.jpg",
    "notas": "Descripcion: VESTIDO CON ESCOTE CRUZADO Y OLANES\nProveedor: NELLY",
    "destacado": 1
  },
  {
    "codigo": "VD 496",
    "descripcion": "VESTIDO DE TIRAS",
    "categoria": "VESTIDO",
    "tela": "POWER SATEN",
    "tallas": "CH - UNITALLA",
    "colores": "VARIADO",
    "foto": "/catalogo/VD496.jpg",
    "notas": "Descripcion: VESTIDO CON ESCOTE CRUZADO EN TIRAS /BIES Y FALDA CON DELATEROS ABIERTOS\nAvios: ETIQUETA PARADA",
    "destacado": 1
  },
  {
    "codigo": "VD 410",
    "descripcion": "VESTIDO CON ARGOLLA",
    "categoria": "VESTIDO",
    "tela": "POWER SATEN",
    "tallas": "CH - M",
    "colores": "NEGRO",
    "foto": "/catalogo/VD410.jpg",
    "notas": "",
    "destacado": 1
  },
  {
    "codigo": "005",
    "descripcion": "VESTIDO MAXI CREPE DE COPAS",
    "categoria": "VESTIDO",
    "tela": "TECNO CREPE",
    "tallas": "GDE - XL",
    "colores": "VARIADO",
    "foto": "/catalogo/005.jpg",
    "notas": "Descripcion: VESTIDO MAXI\nIndicaciones: CONFECCIONAR EN OVER 4",
    "destacado": 1
  },
  {
    "codigo": "PD 46",
    "descripcion": "PANTALON VOGUE",
    "categoria": "PANTALON",
    "tela": "POWER SATEN",
    "tallas": "",
    "colores": "VARIADO",
    "foto": "/catalogo/PD46.jpg",
    "notas": "Descripcion: PANTALON CON PIERNAS",
    "destacado": 1
  },
  {
    "codigo": "NP 284",
    "descripcion": "PANTALON CON FAJO Y HEBILLA",
    "categoria": "PANTALON",
    "tela": "TECNO CREPE",
    "tallas": "M - GDE - XL",
    "colores": "NEGRO",
    "foto": "/catalogo/NP284.jpg",
    "notas": "Descripcion: PANTALON RECTO CON BOLSAS DELANTERAS Y FAJO CON HEBILLA METALICA\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS /0.66MM\nAvios: ETIQUETA PARADA",
    "destacado": 1
  },
  {
    "codigo": "PD 320",
    "descripcion": "PALAZZO CON MOÑO",
    "categoria": "PALAZZO",
    "tela": "TECNO CREPE",
    "tallas": "M - XL",
    "colores": "VARIADO",
    "foto": "/catalogo/PD320.jpg",
    "notas": "Indicaciones: CONFECCIONAR EN OVER 4 HILOS /0.66\nAvios: CINTA DE GEL :35",
    "destacado": 1
  },
  {
    "codigo": "VD 446",
    "descripcion": "VESTIDO PASTELON MAXI",
    "categoria": "VESTIDO",
    "tela": "TECNO CREPE",
    "tallas": "VARIADO",
    "colores": "VARIADO",
    "foto": "/catalogo/VD446.jpg",
    "notas": "Descripcion: VESTIDO CRUZADO",
    "destacado": 1
  },
  {
    "codigo": "CD 281",
    "descripcion": "CHALECO EMBOLSADO Y PANTALON A LA CINTURA",
    "categoria": "CHALECO",
    "tela": "BARBIE TWILL",
    "tallas": "M - GDE - XL",
    "colores": "NEGRO Y BEIGE",
    "foto": "/catalogo/CD281.jpg",
    "notas": "Avios: EN CHALECO :",
    "destacado": 1
  },
  {
    "codigo": "202",
    "descripcion": "BLAZER ¾ DE MANGA",
    "categoria": "BLAZER",
    "tela": "TECNO CREPE",
    "tallas": "VARIADO",
    "colores": "COLORES BASICOS",
    "foto": "/catalogo/202.jpg",
    "notas": "Descripcion: SACO MANGA ¾ CON CUELLO TIPO SMOKING",
    "destacado": 1
  },
  {
    "codigo": "CD 60",
    "descripcion": "CONJUNTO DE BLUSA Y SHORT DE LENTEJUElA",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD60.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "TD 72",
    "descripcion": "BLUSA CON PASTELONES",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/TD72.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 100",
    "descripcion": "CONJUNTO DE SACO CRUZADO Y SHORT BASICO",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD100.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 144",
    "descripcion": "CONJUNTO DE BLUSA MANGA LARGA Y SHORT CON RESORTE EN CINTURA",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD144.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 130",
    "descripcion": "CONJUNTO BLUSA HALTER Y PANTALON PASTELON CENTRO Y RESORTE EN LA PARTE TRASERA",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD130.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 154",
    "descripcion": "VESTIDO DE RESAQUE",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD154.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 165",
    "descripcion": "CONJUNTO CAMISA CORTA Y SHORT CON RESORTE EN LA CINTURA",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD165.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 166",
    "descripcion": "CONJUNTO DE SHORT Y CAMISA MANGA CORTA BRILLOSA",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD166.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 167",
    "descripcion": "CONJUNTO DE BLUSA CORTA CRUZADA Y SHORT CON VUELO",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD167.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "PD 171",
    "descripcion": "PALAZZO DOBLE OLAN",
    "categoria": "PALAZZO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD171.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "MD 172",
    "descripcion": "MONO / ENTERIZO CUELLO BASICO",
    "categoria": "MONO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/MD172.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 182",
    "descripcion": "CONJUNTO DE BLUSA NUDO Y PANTALON BASICO EN SATEN RIGIDO",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD182.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 170",
    "descripcion": "VESTIDO BASICO CON PINZAS EN DELANTERO",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD170.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 176",
    "descripcion": "VESTIDO LARGO CRUZADO Y PLISADO",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD176.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "PD 177",
    "descripcion": "PANTIBLUSA CON PETO CRUZADO",
    "categoria": "PANTIBLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD177.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "PD 209",
    "descripcion": "PALAZZO CRUZADO",
    "categoria": "PALAZZO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD209.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 212",
    "descripcion": "CONJUNTO DE BLUSA Y SHORT BASICO",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD212.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "PD 232",
    "descripcion": "PANTALON DOBLE PINZAS",
    "categoria": "PANTALON",
    "tela": "BARBIE TWILL",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD232.jpg",
    "notas": "Descripcion: PANTALON ESTILO ZARA , CON VIVOS Y PINZAS DOBLES\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS / 0.66",
    "destacado": 0
  },
  {
    "codigo": "BD 222",
    "descripcion": "BLUSA CRUZADA CON MANGA OLAN",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD222.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 246",
    "descripcion": "VESTIDO MAXI CON CAJO EN PARTE TRASERA",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD246.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "SD 250",
    "descripcion": "SACO CON PINZAS Y BOTONES",
    "categoria": "SACO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/SD250.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 252",
    "descripcion": "VESTIDO COMBINADO MESH +POWER SATEN",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD252.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "SD 259",
    "descripcion": "SACO CRUZADO CON BOLSILLOS INVISIBLES",
    "categoria": "SACO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/SD259.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 268",
    "descripcion": "VESTIDO CRUZADO SIN HOMBROS",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD268.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 273",
    "descripcion": "CHAMARRA CON CAPUCHA",
    "categoria": "CHAMARRA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD273.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 275",
    "descripcion": "BLUSA DE RESAQUE METALICA",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD275.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "SD 276",
    "descripcion": "SHORT FALDA CON ABERTURA",
    "categoria": "SHORT",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/SD276.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 279",
    "descripcion": "BLUSA MANGA LARGA COLGANTE",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD279.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "SD 282",
    "descripcion": "SHORT FALDA",
    "categoria": "SHORT",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/SD282.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 297",
    "descripcion": "CONJUNTO DE BLUSA Y FALDA DE OLANES",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD297.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 291",
    "descripcion": "CONJUNTO DE CAMISERA LARGA Y PANTALON DE PIERNAS ANCHAS",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD291.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 293",
    "descripcion": "BLUSA TOP DE 4 OLANES",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD293.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 303",
    "descripcion": "VESTIDO SEMI",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD303.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 306",
    "descripcion": "VESTIDO CON AMARRE EN ESPALDA",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD306.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 309",
    "descripcion": "VESTIDO CON 3 OLANES",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD309.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 308",
    "descripcion": "BLUSA CON AMARRE DELANTERO",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD308.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "PD 206",
    "descripcion": "PANTALON CARGO",
    "categoria": "PANTALON",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD206.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 312",
    "descripcion": "VESTIDO CON RESORTE EN MANGA",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD312.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 313",
    "descripcion": "BLUSA OLANES CUELLO HALTER",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD313.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "SD 314",
    "descripcion": "SHORT CARGO",
    "categoria": "SHORT",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/SD314.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 316",
    "descripcion": "CONJUNTO DE BLUSA CON AMARRE Y SHOR CON RESORTE EN CINTURA COMPLETA",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD316.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 322",
    "descripcion": "TOP CON RESORTE EN COSTADOS",
    "categoria": "TOP",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD322.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 323",
    "descripcion": "VESTIDO CON JARETA EN COSTADO",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD323.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 331",
    "descripcion": "CONJUNTO DE CHALECO Y SHORT/PANTALON CON RESORTE EN PRETINA TRASERA",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD331.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 326",
    "descripcion": "BLUSA CON AMARRE EN TIRANTE",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD326.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "PD 327",
    "descripcion": "PALAZZO CON TIRANTE OLAN JUMPER CON TIRANTE OLAN",
    "categoria": "PALAZZO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD327.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "SD 328",
    "descripcion": "SHORT FALDA CON JARETA DELANTERA",
    "categoria": "SHORT",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/SD328.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 329",
    "descripcion": "BLUSA CON MANGA SEMI",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD329.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 332",
    "descripcion": "VESTIDO COLUMPIO EN PICO",
    "categoria": "VESTIDO",
    "tela": "MESH + FORRO MAGALI",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD332.jpg",
    "notas": "Descripcion: VESTIDO COLUMPIO Y FALDA EN PICO CON RESORTE EN COSTADOS\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS / 0.66 MM\nAvios: ETIQUETA PARADA",
    "destacado": 0
  },
  {
    "codigo": "CD 335",
    "descripcion": "CONJUNTO DE BLUSA Y PANTALON",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD335.jpg",
    "notas": "Descripcion: CONFECCIONAR EN OVER 4 HILOS/0.66MM\nAvios: ETIQUETA HORIZONTAL",
    "destacado": 0
  },
  {
    "codigo": "BD 337",
    "descripcion": "BLUSA CON JARETA EN CENTRO DELANTERO Y SHORT CON PRETINA",
    "categoria": "BLUSA",
    "tela": "LICRA CON TEXTURA",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD337.jpg",
    "notas": "Descripcion: BLUSA CON JARETA Y BABY OVER ACOMPAÑADO DE SHORT BASICO\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS / 0.66MM",
    "destacado": 0
  },
  {
    "codigo": "VD 343",
    "descripcion": "VESTIDO CON OLAN EN SESGO",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD343.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 345",
    "descripcion": "BLUSA BASICA CON CUELLO DELGADO",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD345.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 348",
    "descripcion": "CONJUNTO DE SUPER RIB CHALECO Y PANTALON",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD348.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 351",
    "descripcion": "VESTIDO DE MESH CON OLANES",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD351.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 353",
    "descripcion": "VESTIDO DOBLE FALDA CIRCULAR CON PETO PLISADO",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD353.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 354",
    "descripcion": "BLUSA TIRANTE HALTER",
    "categoria": "BLUSA",
    "tela": "PUNTO DE ROMA",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD354.jpg",
    "notas": "Descripcion: BLUSA TIRANTE\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS / 0.66 MM\nAvios: E PARADA",
    "destacado": 0
  },
  {
    "codigo": "VD 367",
    "descripcion": "VESTIDO MANGA LARGA Y FALDA PLISADA",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD367.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "SD 371",
    "descripcion": "FALDA TABLEADA CON SHORT INCLUIDO",
    "categoria": "FALDA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/SD371.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 374",
    "descripcion": "VESTIDO CORTO CON RESORTE EN FALDA",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD374.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 375",
    "descripcion": "VESTIDO CON UNA MANGA OLAN",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD375.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 382",
    "descripcion": "VESTIDO CON PASTELONES EN ABERTURA",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD382.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "SD 388",
    "descripcion": "ABRIGO CON BOLSAS OCULTAS",
    "categoria": "ABRIGO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/SD388.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 390",
    "descripcion": "VESTIDO CORTE PRINCESA",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD390.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 391",
    "descripcion": "BLUSA CON PLISADO DELANTERO",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD391.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "SD 383",
    "descripcion": "SACO CORTO SIN CRUCE",
    "categoria": "SACO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/SD383.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 398",
    "descripcion": "VESTIDO PETO EN HOMBRO CRUZADO CON FALDA Y 2 PASTELONES",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD398.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 392",
    "descripcion": "VESTIDO NUDO EN FALDA DE LENTEJUELA",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD392.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 397",
    "descripcion": "VESTIDO STRAPPLE GLOBO",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD397.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 399",
    "descripcion": "VESTIDO DE MESH TABLEADO",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD399.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "PD 400",
    "descripcion": "PANTALON VAQUERO RECTO",
    "categoria": "PANTALON",
    "tela": "SEMI LICRA METALICA",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD400.jpg",
    "notas": "Descripcion: PANTALON VAQUERO , CON BOLSAS EN PICO TRASERAS\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS / 0.66 MM\nAvios: CIERRE NORMAL DE 15 CM",
    "destacado": 0
  },
  {
    "codigo": "VD 401",
    "descripcion": "VESTIDO MESH CON OLANES Y VESTIDO INTERIOR",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD401.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "SD 403",
    "descripcion": "SACO LARGO CRUZADO",
    "categoria": "SACO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/SD403.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 404",
    "descripcion": "VESTIDO DE MESH CON UNA MANGA",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD404.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 406",
    "descripcion": "VESTIDO CON CORTE SEMI",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD406.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "PD 408",
    "descripcion": "PANTALON TABLEADO CON RESORTE EN CINTURA",
    "categoria": "PANTALON",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD408.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 409",
    "descripcion": "VESTIDO COLGANTE CON RESORTE EN FALDA TRASERA",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD409.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "PD 411",
    "descripcion": "PALAZZO CON SOLAPA CRUZADA",
    "categoria": "PALAZZO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD411.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 416",
    "descripcion": "VESTIDO ESCOTE CUADRADO",
    "categoria": "VESTIDO",
    "tela": "RAYAS RIB",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD416.jpg",
    "notas": "Descripcion: VESTIDO ESCOTE CUADRADO Y ABERTURA EN FALDA COSTADO IZQUIERDO\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS/0.66MM",
    "destacado": 0
  },
  {
    "codigo": "FD 427",
    "descripcion": "FALDA LINEA A CON MADRES",
    "categoria": "FALDA",
    "tela": "BARBIE TWILL",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/FD427.jpg",
    "notas": "Descripcion: FALDA LINEA A CON 3 MADRES\nIndicaciones: CONFECCIONAR EN OVER 5 HILOS / 1 CM",
    "destacado": 0
  },
  {
    "codigo": "VD 425",
    "descripcion": "VESTIDO GLOBO CON PETO EN HOMBROS",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD425.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 426",
    "descripcion": "VESTIDO STRAPPLE",
    "categoria": "VESTIDO",
    "tela": "LICRA MATE",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD426.jpg",
    "notas": "Descripcion: VESTIDO CON PLISADO EN CINTURA Y TALLE\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS /0.66MM\nAvios: ETIQUETA PARADA",
    "destacado": 0
  },
  {
    "codigo": "CD 423",
    "descripcion": "CONJUNTO DE CHALECO Y SHORT",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD423.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 426-2",
    "descripcion": "VESTIDO OLANES",
    "categoria": "VESTIDO",
    "tela": "CEI",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD426-2.jpg",
    "notas": "Descripcion: VESTIDO CRUZADO CON TRES OLANES\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS / 0.66 MM\nAvios: E. HORIZONTAL\nOJO: en el catalogo del cliente el codigo VD 426 aparece mas de una vez con prendas distintas. Este se renombro para poder cargarlo; hay que definir su codigo real.",
    "destacado": 0
  },
  {
    "codigo": "PD 428",
    "descripcion": "PANTALON BASICO RECTO",
    "categoria": "PANTALON",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD428.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "FD 429",
    "descripcion": "FALDA A LA CADERA",
    "categoria": "FALDA",
    "tela": "BARBIE TWILL",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/FD429.jpg",
    "notas": "Descripcion: FALDA A LA CADERA\nIndicaciones: CONFECCIONAR EN OVER 5 HILOS /1 CM",
    "destacado": 0
  },
  {
    "codigo": "CD 432",
    "descripcion": "CONJUNTO DE CHALECO DE TIRANTE + PANTALON A LA CINTURA",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD432.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 435",
    "descripcion": "BLUSA DE OLANES HORIZONTALES",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD435.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 436",
    "descripcion": "BLUSA ASIMETRICA EN PICO",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD436.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 437",
    "descripcion": "BLUSA PLISADA DE TIRANTES",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD437.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 438",
    "descripcion": "CONJUNTO DE BLUSA MANGA LARGA ABIERTA Y TOP BASICO NEGRO",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD438.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 439",
    "descripcion": "CONJUNTO DE BLUSA CON AMARRE + PANTALON CON PASTELONES Y RESORTE",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD439.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 440",
    "descripcion": "VESTIDO CRUZADO CON SHORT",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD440.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 442",
    "descripcion": "CONJUNTO DE CHALECO Y SHORT BASICO",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD442.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "SD 443",
    "descripcion": "SHORT CON PASTELONES",
    "categoria": "SHORT",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/SD443.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 465",
    "descripcion": "BLUSA CON ESCOTE EN HOMBROS",
    "categoria": "BLUSA",
    "tela": "RIB",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD465.jpg",
    "notas": "Descripcion: BLUSA CON ESCOTE EN HOMBROS\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS /0.66 MM",
    "destacado": 0
  },
  {
    "codigo": "VD 447",
    "descripcion": "VESTIDO HALTER RECTO",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD447.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 449",
    "descripcion": "CONJUNTO DE BLUSA NUDO Y FALDA CON ABERTURA EN COSATDO IZQUIERDO",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD449.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 450",
    "descripcion": "VESTIDO STRAPPLE CON FLOR EN CENTRO",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD450.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 451",
    "descripcion": "VESTIDO CON ESCOTE CRUZADO Y SHORT",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD451.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "CD 452",
    "descripcion": "CONJUNTO DE BLUSA DE TIRANTES Y SHORT FALDA",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD452.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 456",
    "descripcion": "BLUSA ESCOTE CRUZADO Y PLISADO",
    "categoria": "BLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD456.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "PD 464",
    "descripcion": "PALAZZO STRAPPLE CON RESORTE",
    "categoria": "PALAZZO",
    "tela": "LICRA CON TEXTURA",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD464.jpg",
    "notas": "Descripcion: PALAZZO CON BOLSAS DE COSTADO Y STRAPPLE\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS / 0.66\nAvios: ETIQUETA PARADA",
    "destacado": 0
  },
  {
    "codigo": "PD 466",
    "descripcion": "PANTIBLUSA MANGA CORTA",
    "categoria": "PANTIBLUSA",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD466.jpg",
    "notas": "Indicaciones: CONFECCIONAR EN OVER 4 HILOS / 0.66MM",
    "destacado": 0
  },
  {
    "codigo": "PD 471",
    "descripcion": "PALAZZO RESACADO",
    "categoria": "PALAZZO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD471.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "BD 413",
    "descripcion": "BLUSA ESCOTE CRUZADO",
    "categoria": "BLUSA",
    "tela": "RIB",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/BD413.jpg",
    "notas": "Descripcion: BLUSA ESCOTE CRUZADO CON MANGA CORTA / LARGA\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS",
    "destacado": 0
  },
  {
    "codigo": "CD 479",
    "descripcion": "CONJUNTO DE BLUSA MANGA LARGA Y FALDA LARGA",
    "categoria": "CONJUNTO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/CD479.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "VD 478",
    "descripcion": "VESTIDO DOBLE FALDA CIRCULAR",
    "categoria": "VESTIDO",
    "tela": "",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD478.jpg",
    "notas": "",
    "destacado": 0
  },
  {
    "codigo": "JD 484",
    "descripcion": "JUMPER CON SOBREFALDA",
    "categoria": "JUMPER",
    "tela": "TECNO CREPE",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/JD484.jpg",
    "notas": "Descripcion: JUMPER CON PASTELONES EN TALLE , CORTE PRINCESA\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS / 0.66MM",
    "destacado": 0
  },
  {
    "codigo": "VD 488",
    "descripcion": "VESTIDO MAXI CON MANGA LARGA",
    "categoria": "VESTIDO",
    "tela": "POWER SATEN",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD488.jpg",
    "notas": "Descripcion: VESTIDO ESCOTE CRUZADO CON FALDA PLISADA\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS/0.66\nAvios: ETIQUETA PARADA",
    "destacado": 0
  },
  {
    "codigo": "PD 489",
    "descripcion": "PALAZZO CON 3 OLANES INCRUSTADOS",
    "categoria": "PALAZZO",
    "tela": "TECNO CREPE",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD489.jpg",
    "notas": "Descripcion: PALAZZO CON 3 OLANES INCRUSTADOS\nIndicaciones: CONFECCIONAR EN OVER 4",
    "destacado": 0
  },
  {
    "codigo": "VD 490",
    "descripcion": "VESTIDO CRUZADO CON FALDA PLISADA",
    "categoria": "VESTIDO",
    "tela": "POWER SATEN",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD490.jpg",
    "notas": "Descripcion: VESTIDO CRUZADO CON FALDA PLISADO EN ENTRECOSTADO DERECHO\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS / 0.66MM",
    "destacado": 0
  },
  {
    "codigo": "VD 492",
    "descripcion": "VESTIDO CON 3 OLANES",
    "categoria": "VESTIDO",
    "tela": "POWER SATEN",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/VD492.jpg",
    "notas": "Descripcion: VESTIDO CON PETO Y 3 OLANES\nAvios: ETIQUETA PARADA",
    "destacado": 0
  },
  {
    "codigo": "PD 498",
    "descripcion": "PANTIBLUSA BASICA DE ENCAJE",
    "categoria": "PANTIBLUSA",
    "tela": "ENCAJE",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD498.jpg",
    "notas": "Descripcion: PANTIBLUSA ESCOTE REDONDO\nIndicaciones: CONFECCIONAR EN OVER DE 4 HILOS / 0.66MM\nAvios: ETIQUETA HORIZONTAL",
    "destacado": 0
  },
  {
    "codigo": "PD 504",
    "descripcion": "PANTIBLUSA DE ARGOLLA",
    "categoria": "PANTIBLUSA",
    "tela": "LICRA SATEN Y VACA",
    "tallas": "",
    "colores": "",
    "foto": "/catalogo/PD504.jpg",
    "notas": "Descripcion: PANTIBLUSA CON JARETA EN HOMBRO Y COSTADO\nIndicaciones: CONFECCIONAR EN OVER 4 HILOS / 0.66 MM",
    "destacado": 0
  }
];
